FORMAT: 1A

# MT PA 1 Student Routing
This document is being used a quick an easy way to document MT3 current Gradebook Services API.

## API [/api]
### Hypermedia API [GET]
+ Response 200 (application/json)

        {
            "_link":{
                    "self": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/api"
                    },
                    "activeUserInfo": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/user/short/me"
                    },
                    "activeUserSettings": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/nb/service/userSettings?jsonKey=:jsonKey"
                    },
                    "singleUserInfo": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/user/short/:snapshotId/:userId"
                    },
                    "courseInfo": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/courseInfo/:snapshotId"
                    },
                    "activityTree": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/itemsTreeWithSummaries/:snapshotId"
                    },
                    "activityGrouping": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/groupedItems/:snapshotId"
                    },
                    "activityCategoriesAndWeighting": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/bulk/itemsByCategory/:snapshotId"
                    },
                    "activityOverridesAllStudents": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/items/useroverride/:snapshotId"
                    },
                    "allActivityCommentsSingleStudent": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/nb/service/activityComment/snapshot/:snapshotId/user/:userId"
                    },
                    "allActivityFeatures": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/appActivities/:snapshotId"
                    },
                    "courseScoreAllStudents": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/studentSummaries/:snapshotId"
                    },
                    "courseScoreSingleStudent": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/studentSummaries/:snapshotId/user/:userId"
                    },
                    "activityScoresRangeOfStudents": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/outcome/:snapshotId?userIds=[:userIds]"
                    },
                    "activityAttemptsSingleStudent": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/:snapshotId/attempt/:activityId/user/:userId"
                    },
                    "activityCommentsSingleStudent": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/nb/service/activityComment/find?userId=:userId&activityId=:activityId&sort=lastModifiedDate+desc"
                    },
                    "studentScoreBreakDown": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/scores/:snapshotId/user/:userId/summary"
                    },
                    "myScoreBreakDown": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/progressapp/service/scores/:snapshotId/user/me/summary"
                    },
                    "provisionedApps": {
                        "href": "http://private-e09bb-mt4progress.apiary-mock.com/nb/service/appAction/snapshot/:snapshotId/apps"
                    }
            }
        }
        
# Group Student Grades
## All Course Grades [/progressapp/service/studentSummaries/{snapshotId}]
### List all student course grades [GET]
+ Response 200 (application/json)

        {
            "timestamp": 1428945188363,
            "studentSummaries": [
                {
                    "firstName": "Mock 1",
                    "lastName": "Student",
                    "email": "userone@ng.com",
                    "studentId": "87787",
                    "orgId": 13414,
                    "userId": 929,
                    "sourceId": "5cdc7afabbc6f418:-49ff5186:13093bc2109:-7e38",
                    "finalScore": 46.5,
                    "pointsPossible": 847,
                    "pointsEarned": 214
                }
            ]
        }
        
## All Activity Grades [/progressapp/service/outcome/{snapshotId}?userIds=%5B{studentIds}%5D]
### List all students activity grades [GET]
+ Response 200 (application/json)

        {
            "929": [
                {
                    "pointsEarned": 0,
                    "pointsPossible": 23,
                    "recordedPercent": 0,
                    "activityId": 2170043,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 6,
                    "pointsPossible": 10,
                    "recordedPercent": 60,
                    "activityId": 2572817,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 95,
                    "pointsPossible": 100,
                    "recordedPercent": 95,
                    "activityId": 2729677,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 41,
                    "pointsPossible": 60,
                    "recordedPercent": 68.3,
                    "activityId": 2743921,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 2,
                    "recordedPercent": 0,
                    "activityId": 1958799,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 1,
                    "pointsPossible": 1,
                    "recordedPercent": 100,
                    "activityId": 1958796,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 9,
                    "pointsPossible": 10,
                    "recordedPercent": 90,
                    "activityId": 1958797,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 21,
                    "pointsPossible": 22,
                    "recordedPercent": 95.5,
                    "activityId": 1958794,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 3,
                    "pointsPossible": 3,
                    "recordedPercent": 100,
                    "activityId": 1958795,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 27,
                    "recordedPercent": 0,
                    "activityId": 1958792,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 9,
                    "pointsPossible": 12,
                    "recordedPercent": 75,
                    "activityId": 1958793,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 22,
                    "recordedPercent": 0,
                    "activityId": 1958805,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 13,
                    "recordedPercent": 0,
                    "activityId": 1958804,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 7,
                    "recordedPercent": 0,
                    "activityId": 1958803,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 35,
                    "recordedPercent": 0,
                    "activityId": 1958802,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 10,
                    "recordedPercent": 0,
                    "activityId": 1958800,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 2,
                    "recordedPercent": 0,
                    "activityId": 1958838,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 100,
                    "recordedPercent": 0,
                    "activityId": 2740088,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 75,
                    "recordedPercent": 0,
                    "activityId": 3244017,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 11,
                    "recordedPercent": 0,
                    "activityId": 1958814,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 22,
                    "recordedPercent": 0,
                    "activityId": 1958813,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 2,
                    "recordedPercent": 0,
                    "activityId": 1958811,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 23,
                    "recordedPercent": 0,
                    "activityId": 1958810,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 16,
                    "recordedPercent": 0,
                    "activityId": 1958816,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 9,
                    "pointsPossible": 12,
                    "recordedPercent": 75,
                    "activityId": 1958826,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 35,
                    "pointsPossible": 35,
                    "recordedPercent": 100,
                    "activityId": 1958840,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 3,
                    "pointsPossible": 10,
                    "recordedPercent": 30,
                    "activityId": 1958788,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 100,
                    "recordedPercent": 0,
                    "activityId": 4199575,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 75,
                    "recordedPercent": 0,
                    "activityId": 3758848,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 100,
                    "recordedPercent": 0,
                    "activityId": 4581128,
                    "attemptCount": 0
                },
                {
                    "pointsEarned": 0,
                    "pointsPossible": 5,
                    "recordedPercent": 0,
                    "activityId": 4581129,
                    "attemptCount": 0
                }
            ]
        }