FORMAT: 1A

# MT PA 1 Student Routing
This document is being used a quick an easy way to document MT3 current Gradebook Services API.

## API [/api]
### Hypermedia API [GET]
+ Response 200 (application/json)

        {
            "_link":{
                    "self": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/api"
                    },
                    "activeUserInfo": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/user/short/me"
                    },
                    "activeUserSettings": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/nb/service/userSettings?jsonKey=:jsonKey"
                    },
                    "singleUserInfo": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/user/short/:snapshotId/:userId"
                    },
                    "courseInfo": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/courseInfo/:snapshotId"
                    },
                    "activityTree": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/itemsTreeWithSummaries/:snapshotId"
                    },
                    "activityGrouping": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/groupedItems/:snapshotId"
                    },
                    "activityCategoriesAndWeighting": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/bulk/itemsByCategory/:snapshotId"
                    },
                    "activityOverridesAllStudents": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/items/useroverride/:snapshotId"
                    },
                    "allActivityCommentsSingleStudent": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/nb/service/activityComment/snapshot/:snapshotId/user/:userId"
                    },
                    "allActivityFeatures": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/appActivities/:snapshotId"
                    },
                    "courseScoreAllStudents": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/studentSummaries/:snapshotId"
                    },
                    "courseScoreSingleStudent": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/studentSummaries/:snapshotId/user/:userId"
                    },
                    "activityScoresRangeOfStudents": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/outcome/:snapshotId?userIds=[:userIds]"
                    },
                    "activityAttemptsSingleStudent": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/:snapshotId/attempt/:activityId/user/:userId"
                    },
                    "activityCommentsSingleStudent": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/nb/service/activityComment/find?userId=:userId&activityId=:activityId&sort=lastModifiedDate+desc"
                    },
                    "studentScoreBreakDown": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/scores/:snapshotId/user/:userId/summary"
                    },
                    "myScoreBreakDown": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/progressapp/service/scores/:snapshotId/user/me/summary"
                    },
                    "provisionedApps": {
                        "href": "http://private-857c47-classicmtgradebookservices.apiary-mock.com/nb/service/appAction/snapshot/:snapshotId/apps"
                    }
            }
        }